<?php



/**
 * ActivityLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityLogRepository extends Doctrine\ORM\EntityRepository
{
}
