<?php



/**
 * DepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartmentRepository extends Doctrine\ORM\EntityRepository
{
    public static function instance(): DepartmentRepository
    {
        return new static(GetEntityManager(), GetEntityManager()->getClassMetadata('Department'));
    }

    public function find($id, $lockMode = null, $lockVersion = null) : Department
    {
        return parent::find($id, $lockMode, $lockVersion); // TODO: Change the autogenerated stub
    }
}
