<?php



/**
 * EmployeeLeaveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeLeaveRepository extends Doctrine\ORM\EntityRepository
{
}
