<?php

use Doctrine\Common\Collections\ArrayCollection;


/**
 * EmployeeLeaveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeLeaveRepository extends Doctrine\ORM\EntityRepository
{
    public static function instance(): EmployeeLeaveRepository
    {
        return new static(GetEntityManager(), GetEntityManager()->getClassMetadata('EmployeeLeave'));
    }

    public function findBy(array $criteria, ?array $orderBy = null, $limit = null, $offset = null) : ArrayCollection | array
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }

    public function find($id, $lockMode = null, $lockVersion = null) : EmployeeLeave | null
    {
        return parent::find($id, $lockMode, $lockVersion);
    }
}
