<?php



/**
 * UserSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSessionRepository extends Doctrine\ORM\EntityRepository
{
}
