<?php

use Doctrine\ORM\EntityManager;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends Doctrine\ORM\EntityRepository
{


    public static function instance(): UserRepository
    {
       return new self(GetEntityManager(), GetEntityManager()->getClassMetadata('User'));
    }

    /**
     * @param array $criteria
     * @param array|null $orderBy
     * @param null $limit
     * @param null $offset
     * @return array|User[]
     */
    public function findBy(array $criteria, ?array $orderBy = null, $limit = null, $offset = null): array
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }

    public function findOneBy(array $criteria, ?array $orderBy = null): User|null
    {
        return parent::findOneBy($criteria, $orderBy);
    }
}

