<?php



/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends Doctrine\ORM\EntityRepository
{
    public function findBy(array $criteria, ?array $orderBy = null, $limit = null, $offset = null)
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset); // TODO: Change the autogenerated stub
    }

    /**
     * @throws \Doctrine\ORM\OptimisticLockException
     * @throws \Doctrine\ORM\TransactionRequiredException
     * @throws \Doctrine\ORM\Exception\ORMException
     */
    public function testFindById($criteria = ['user_id', 4])
    {
        $entityManager = GetEntityManager();
        $user = $entityManager->find('User', $criteria['user_id']);

    }

    public static function findByEmail($criteria = ['email', 'user@ems.com'])
    {
        // user whose email = user@ems.com
    }

}

